# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 517)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0.051, x2:1, y2:1, stop:0.102273 rgba(21, 46, 21, 255), stop:1 rgba(171, 255, 182, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 440, 401, 51))
        self.pushButton.setSizeIncrement(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setTabletTracking(True)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.514, cy:0.422631, radius:0.504, fx:0.766, fy:0.283184, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(255, 170, 0, 255));\n"
"gridline-color: rgb(0, 170, 0);\n"
"\n"
"border-color: rgb(64, 255, 6);\n"
"border-radius: 10")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 391, 41))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.514, cy:0.422631, radius:0.504, fx:0.766, fy:0.283184, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(255, 170, 0, 255));\n"
"font: 87 14pt \"Arial Black\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"border-color: rgb(64, 255, 6);\n"
"border-radius: 10")
        self.textEdit.setObjectName("textEdit")
        self.Name_work = QtWidgets.QLabel(self.centralwidget)
        self.Name_work.setGeometry(QtCore.QRect(10, 20, 391, 21))
        self.Name_work.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.514, cy:0.422631, radius:0.504, fx:0.766, fy:0.283184, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(255, 170, 0, 255));\n"
"font: 87 14pt \"Arial Black\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"qproperty-alignment: AlignCenter;\n"
"border-color: rgb(64, 255, 6);\n"
"border-radius: 7")
        self.Name_work.setObjectName("Name_work")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 391, 21))
        self.label_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.514, cy:0.422631, radius:0.504, fx:0.766, fy:0.283184, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(255, 170, 0, 255));\n"
"font: 87 14pt \"Arial Black\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"qproperty-alignment: AlignCenter;\n"
"border-color: rgb(64, 255, 6);\n"
"border-radius: 7")
        self.label_2.setObjectName("label_2")
        self.type_work = QtWidgets.QComboBox(self.centralwidget)
        self.type_work.setGeometry(QtCore.QRect(10, 150, 391, 41))
        self.type_work.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.514, cy:0.422631, radius:0.504, fx:0.766, fy:0.283184, stop:0 rgba(255, 140, 0, 255), stop:1 rgba(255, 170, 0, 255));\n"
"font: 87 14pt \"Arial Black\";\n"
"gridline-color: rgb(0, 170, 0);\n"
"qproperty-alignment: AlignCenter;\n"
"border-color: rgb(64, 255, 6);\n"
"border-radius: 10")
        self.type_work.setObjectName("type_work")
        self.type_work.addItem("")
        self.type_work.addItem("")
        self.type_work.addItem("")
        self.type_work.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
        self.Name_work.setText(_translate("MainWindow", "Название объекта"))
        self.label_2.setText(_translate("MainWindow", "Тип Работ"))
        self.type_work.setItemText(0, _translate("MainWindow", "Аттестация"))
        self.type_work.setItemText(1, _translate("MainWindow", "Контрольная проверка"))
        self.type_work.setItemText(2, _translate("MainWindow", "Тестирование"))
        self.type_work.setItemText(3, _translate("MainWindow", "Доп испытания"))